print(" IT WAS A DARK AND STORMY NIGHT.")
print("")
print("In her attic bedroom Margaret Murry, wrapped in an old patchwork quilt, sat on the foot of her")
print("bed and watched the trees tossing in the frenzied lashing of the wind. Behind the trees clouds")
print("scudded frantically across the sky. Every few moments the moon ripped through them, creating ")
print("wraithlike shadows that raced along the ground.")
